name: insightops_dart
description: Unofficial wrapper for using Rapid7 insightOps logs (former LogEntries) with Dart.
version: 0.2.0
homepage: https://github.com/ookami-kb/insightops_dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  async: ^2.5.0
  http: ^0.13.0
  logging: ^1.0.0

dev_dependencies:
  mews_pedantic: ^0.1.2
  test: ^1.16.5
